baseurl = "http://www.example.com"
title = "Pavel Shibaev"

theme = "coder-portfolio"

DefaultContentLanguage = "en"

paginate = 20

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
pygmentsUseClasses = true

disqusShortname = "yourdiscussshortname"

[params]
    author = "Pavel Shibaev"
    description = "Pavel Shibaev's personal website"
    keywords = "blog,developer,personal"
    info = "STUDENT, PYTHON ENGINEER"
    avatarurl = "images/avatar.jpg"
    footercontent = "Enter a text here."
    fixedbarContent = "Need additional contact?→"
    fixedbarContentAfter = "Thank You! Save, share & like→"

    hideCredits = false
    hideCopyright = false

    snsShare = true

    thumbnail = "images/tn.png"

    # Custom CSS
    custom_css = []

    # Alignment of Mobile Menu items
    itemscentered = true

    # RTL support
    rtl = false

    langseparator = "|"

# TODO: add more social links here
[[params.social]]
    name = "Github"
    weight = 1
    url = "https://github.com/shibaeff"

[[params.social]]
    name = "VK"
    weight = 2
    url = "https://vk.com/paulpalich"


[languages]
    [languages.en]
        languagecode = "en"
        languagename = "English" # The language name to be displayed in the selector.
        title = "Pavel Shibaev"

        # You can configure the theme parameter for each language.
        [languages.en.params]
            author = "Pavel Shibaev"
            info = "PYTHON ENGINEER AND STUDENT"
            description = "Pavel Shibaev's personal website"
            keywords = "blog,developer,personal"

        [languages.en.menu] # It is possible to change the menu too.

            [[languages.en.menu.main]]
                name = "About"
                weight = 1.0
                url = "about"

            [[languages.en.menu.main]]
                name = "About"
                weight = 1.5
                url = "CV"

            [[languages.en.menu.main]]
                name = "Blog"
                weight = 2.0
                url = "posts"

            [[languages.en.menu.main]]
                name = "Projects"
                weight = 3
                url = "projects"
            [[languages.en.menu.main]]
                name = "Contact me"
                weight = 5
                url = "contact"


    [languages.ru]
        languagecode = "ru"
        languagename = "russian"
        title = "Блог, личный сайт"

        [languages.ru.params]
            author = "Павел Шибаев"
            description = "Здесь вы узнаете больше обо мне"
            keywords = "блог, разработчик"
            info = "ПИШУ НА PYTHON & УЧУСЬ"

        [languages.ru.menu]
            [[languages.ru.menu.main]]
                name = "Обо мне"
                weight = 1.0
                url = "ru/about"
            
            [[languages.en.menu.main]]
                name = "About"
                weight = 1.5
                url = "Резюме"

            [[languages.ru.menu.main]]
                name = "Посты"
                weight = 2.0
                url = "ru/posts"
            [[languages.ru.menu.main]]
                name = "Проекты"
                weight = 3
                url = "ru/projects"
            [[languages.ru.menu.main]]
                name = "Контакты"
                weight = 5
                url = "ru/contact"
